"""Generic XBRL XML generator.

Takes:
  - extracted JSON data (from XBRLDataExtractor)
  - context_template.yml (envelope, contexts, units, schema_ref)
  - taxonomy_mapping.yml (JSON path -> XBRL element)

Emits a complete XBRL instance document as a UTF-16 string.

Country-agnostic: swap the two YAML files to support a different jurisdiction.
"""
from __future__ import annotations

import datetime as dt
import logging
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from xml.sax.saxutils import escape

import yaml

logger = logging.getLogger(__name__)


# ── helpers ───────────────────────────────────────────────────────────────────

def _get(data: dict, path: str) -> Any:
    """Traverse dotted path. Returns None if any segment missing."""
    if not path:
        return None
    cur = data
    for seg in path.split("."):
        if isinstance(cur, dict) and seg in cur:
            cur = cur[seg]
        else:
            return None
    return cur


def _fmt_number(value: Any, decimals: int) -> str:
    """Format a number for XBRL emission. Integers stay integer; decimals fixed."""
    if value is None:
        return ""
    if decimals == 0:
        return str(int(round(float(value))))
    return f"{float(value):.{decimals}f}"


def _esc(value: Any) -> str:
    """XML-escape a value for use as text content."""
    if value is None:
        return ""
    return escape(str(value))


def _esc_attr(value: Any) -> str:
    """XML-escape a value for use as an attribute value."""
    if value is None:
        return ""
    return escape(str(value), {'"': "&quot;"})


@dataclass
class GenerationResult:
    success: bool
    xml: str = ""
    filename: str = ""
    fact_count: int = 0
    context_count: int = 0
    error: str = ""


# ── main class ────────────────────────────────────────────────────────────────

class IndianXBRLGenerator:
    """Generate an Indian-format XBRL XML document from extracted JSON."""

    def __init__(self, context_template_path: str | Path, mapping_path: str | Path):
        with open(context_template_path, "r", encoding="utf-8") as f:
            self.tpl = yaml.safe_load(f)
        with open(mapping_path, "r", encoding="utf-8") as f:
            self.mapping = yaml.safe_load(f)
        self.mappings = self.mapping.get("mappings", {})

    # ── public API ────────────────────────────────────────────────────────────

    def generate(self, data: dict) -> GenerationResult:
        try:
            xml_str = self._build_xml(data)
            filename = self._build_filename(data)
            # Count facts emitted (rough — counts opening tags of in-gaap or in-ca)
            fact_count = len(re.findall(r"<in-(?:gaap|ca|ca-ent)[^>]*contextRef=", xml_str))
            context_count = xml_str.count("<xbrli:context ")
            return GenerationResult(
                success=True,
                xml=xml_str,
                filename=filename,
                fact_count=fact_count,
                context_count=context_count,
            )
        except Exception as exc:
            logger.exception("XBRL generation failed")
            return GenerationResult(success=False, error=str(exc))

    # ── XML construction ─────────────────────────────────────────────────────

    def _build_xml(self, data: dict) -> str:
        encoding = self.tpl.get("encoding", "utf-16")
        gen_comment = self.tpl.get("generator_comment", "Generated by Tawthiq")
        parts: list[str] = []
        parts.append(f'<?xml version="1.0" encoding="{encoding}"?>')
        parts.append(f"<!--{gen_comment}-->")
        parts.append(self._open_root())
        parts.append(self._build_schema_ref())
        parts.extend(self._build_standard_contexts(data))
        # Collect dimensional contexts used by facts so we don't emit unused ones
        contexts_used, dim_context_blocks = self._build_dimensional_contexts(data)
        parts.extend(dim_context_blocks)
        parts.extend(self._build_units())
        parts.extend(self._build_facts(data, contexts_used))
        parts.append("</xbrli:xbrl>")
        return "\n".join(parts)

    def _open_root(self) -> str:
        ns = self.tpl.get("namespaces", {})
        # Emit namespaces sorted but with xbrli first (matches typical C2X output)
        priority = ["in-gaap", "in-ca", "in-ca-ent", "negated", "xlink", "xbrli", "link",
                    "ref", "nonnum", "xbrldt", "in-ca-types", "num",
                    "in-ca-roles", "xsi", "net", "xbrldi", "xl", "iso4217",
                    "in-gaap-roles", "in-ci-ent"]
        # de-dupe while preserving order
        seen: set[str] = set()
        ordered: list[str] = []
        for p in priority + list(ns.keys()):
            if p in ns and p not in seen:
                seen.add(p)
                ordered.append(p)
        attrs = " ".join(f'xmlns:{prefix}="{_esc_attr(ns[prefix])}"' for prefix in ordered)
        return f"<xbrli:xbrl {attrs}>"

    def _build_schema_ref(self) -> str:
        href = self.tpl.get("schema_ref", "")
        return f'    <link:schemaRef xlink:type="simple" xlink:href="{_esc_attr(href)}" />'

    # ── contexts ─────────────────────────────────────────────────────────────

    def _build_standard_contexts(self, data: dict) -> list[str]:
        cin = _get(data, "company.cin") or ""
        scheme = self.tpl.get("entity", {}).get("scheme", "")
        contexts = self.tpl.get("contexts", {})
        blocks: list[str] = []
        for ctx_id, defn in contexts.items():
            period_xml = self._period_xml(defn, data)
            if period_xml is None:
                continue  # skip context if dates not available
            blocks.append(self._context_block(ctx_id, scheme, cin, period_xml))
        return blocks

    def _period_xml(self, defn: dict, data: dict) -> str | None:
        ptype = defn.get("type")
        if ptype == "duration":
            start = _get(data, defn["start_date_source"])
            end = _get(data, defn["end_date_source"])
            if not start or not end:
                return None
            return (f"        <xbrli:period>\n"
                    f"            <xbrli:startDate>{_esc(start)}</xbrli:startDate>\n"
                    f"            <xbrli:endDate>{_esc(end)}</xbrli:endDate>\n"
                    f"        </xbrli:period>")
        if ptype == "instant":
            d = _get(data, defn["date_source"])
            if not d:
                return None
            return (f"        <xbrli:period>\n"
                    f"            <xbrli:instant>{_esc(d)}</xbrli:instant>\n"
                    f"        </xbrli:period>")
        return None

    def _context_block(self, ctx_id: str, scheme: str, cin: str, period_xml: str,
                       scenario_xml: str = "") -> str:
        scenario_block = f"\n        <xbrli:scenario>\n{scenario_xml}\n        </xbrli:scenario>" if scenario_xml else ""
        return (
            f'    <xbrli:context id="{_esc_attr(ctx_id)}">\n'
            f"        <xbrli:entity>\n"
            f'            <xbrli:identifier scheme="{_esc_attr(scheme)}">{_esc(cin)}</xbrli:identifier>\n'
            f"        </xbrli:entity>\n"
            f"{period_xml}"
            f"{scenario_block}\n"
            f"    </xbrli:context>"
        )

    # ── dimensional contexts (built on demand) ────────────────────────────────

    def _build_dimensional_contexts(self, data: dict) -> tuple[set[str], list[str]]:
        """Build only the dimensional contexts that we actually need for facts.

        Returns (set of context ids used, list of context XML blocks).
        """
        cin = _get(data, "company.cin") or ""
        scheme = self.tpl.get("entity", {}).get("scheme", "")
        used_ids: set[str] = set()
        blocks: list[str] = []

        # Shareholders → Tab_D_CY_309_{idx}, Tab_I_CY_309_{idx}
        for i, _sh in enumerate(data.get("shareholders") or [], start=1):
            for ctx_id, period_xml in self._shareholder_context_xmls(data, i):
                if ctx_id in used_ids:
                    continue
                used_ids.add(ctx_id)
                scenario_xml = self._typed_member_scenario(
                    "in-gaap:NameOfShareholderAxis", f"Shareholder{i}"
                )
                blocks.append(self._context_block(ctx_id, scheme, cin, period_xml, scenario_xml))

        # Directors → KeyManagerialPersonnelsAndDirectorsDomain_D_CY_{idx}
        for i, _dir_ in enumerate(data.get("directors") or [], start=1):
            ctx_id = f"KeyManagerialPersonnelsAndDirectorsDomain_D_CY_{i}"
            if ctx_id in used_ids:
                continue
            used_ids.add(ctx_id)
            period_xml = (
                f"        <xbrli:period>\n"
                f"            <xbrli:startDate>{_esc(_get(data, 'reporting_period.start_date'))}</xbrli:startDate>\n"
                f"            <xbrli:endDate>{_esc(_get(data, 'reporting_period.end_date'))}</xbrli:endDate>\n"
                f"        </xbrli:period>"
            )
            scenario_xml = self._typed_member_scenario(
                "in-ca:KeyManagerialPersonnelsAndDirectorsAxis", f"Director{i}"
            )
            blocks.append(self._context_block(ctx_id, scheme, cin, period_xml, scenario_xml))

        # Auditors → AuditorsDomain_D_CY_3066_1_{idx} (one per auditor; we treat the single
        # auditor structure as 1 auditor — multi-auditor support requires array in extraction)
        auditor = data.get("auditor")
        if isinstance(auditor, dict):
            ctx_id = "AuditorsDomain_D_CY_3066_1_1"
            if ctx_id not in used_ids:
                used_ids.add(ctx_id)
                period_xml = (
                    f"        <xbrli:period>\n"
                    f"            <xbrli:startDate>{_esc(_get(data, 'reporting_period.start_date'))}</xbrli:startDate>\n"
                    f"            <xbrli:endDate>{_esc(_get(data, 'reporting_period.end_date'))}</xbrli:endDate>\n"
                    f"        </xbrli:period>"
                )
                scenario_xml = self._typed_member_scenario("in-ca:AuditorsAxis", "1")
                blocks.append(self._context_block(ctx_id, scheme, cin, period_xml, scenario_xml))

        # Share-capital classes → Tab_*_198_{idx}
        classes = (_get(data, "share_capital.issued_subscribed_paidup.classes") or [])
        for i, _cls in enumerate(classes, start=1):
            for ctx_id, period_xml in self._share_class_context_xmls(data, i):
                if ctx_id in used_ids:
                    continue
                used_ids.add(ctx_id)
                scenario_xml = self._explicit_member_scenario(
                    "in-gaap:ClassesOfShareCapitalAxis", f"in-gaap:EquityShares{i}Member"
                )
                blocks.append(self._context_block(ctx_id, scheme, cin, period_xml, scenario_xml))

        return used_ids, blocks

    def _shareholder_context_xmls(self, data: dict, idx: int) -> list[tuple[str, str]]:
        """Return [(ctx_id, period_xml), ...] for a single shareholder index."""
        cy_start = _get(data, "reporting_period.start_date")
        cy_end = _get(data, "reporting_period.end_date")
        out = []
        # Duration CY
        if cy_start and cy_end:
            out.append((
                f"Tab_D_CY_309_{idx}",
                f"        <xbrli:period>\n"
                f"            <xbrli:startDate>{_esc(cy_start)}</xbrli:startDate>\n"
                f"            <xbrli:endDate>{_esc(cy_end)}</xbrli:endDate>\n"
                f"        </xbrli:period>",
            ))
        # Instant CY (period-end)
        if cy_end:
            out.append((
                f"Tab_I_CY_309_{idx}",
                f"        <xbrli:period>\n"
                f"            <xbrli:instant>{_esc(cy_end)}</xbrli:instant>\n"
                f"        </xbrli:period>",
            ))
        return out

    def _share_class_context_xmls(self, data: dict, idx: int) -> list[tuple[str, str]]:
        cy_start = _get(data, "reporting_period.start_date")
        cy_end = _get(data, "reporting_period.end_date")
        out = []
        if cy_end:
            out.append((
                f"Tab_I_CY_198_{idx}",
                f"        <xbrli:period>\n"
                f"            <xbrli:instant>{_esc(cy_end)}</xbrli:instant>\n"
                f"        </xbrli:period>",
            ))
        return out

    def _typed_member_scenario(self, dimension: str, value: str) -> str:
        return (
            f'            <xbrldi:typedMember dimension="{_esc_attr(dimension)}">\n'
            f"                <in-ca:KeyManagerialPersonnelsAndDirectorsDomain>{_esc(value)}</in-ca:KeyManagerialPersonnelsAndDirectorsDomain>\n"
            f"            </xbrldi:typedMember>"
        )

    def _explicit_member_scenario(self, dimension: str, member: str) -> str:
        return (
            f'            <xbrldi:explicitMember dimension="{_esc_attr(dimension)}">{_esc(member)}</xbrldi:explicitMember>'
        )

    # ── units ────────────────────────────────────────────────────────────────

    def _build_units(self) -> list[str]:
        units = self.tpl.get("units", {})
        blocks = []
        for uid, defn in units.items():
            blocks.append(
                f'    <xbrli:unit id="{_esc_attr(uid)}">\n'
                f"        <xbrli:measure>{_esc(defn['measure'])}</xbrli:measure>\n"
                f"    </xbrli:unit>"
            )
        return blocks

    # ── facts ────────────────────────────────────────────────────────────────

    def _build_facts(self, data: dict, dim_contexts_available: set[str]) -> list[str]:
        blocks: list[str] = []
        for path, spec in self.mappings.items():
            if not isinstance(spec, dict):
                continue
            if spec.get("special") == "entity_identifier":
                continue  # already emitted in <xbrli:identifier>
            if "[*]" in path:
                # Array-typed mapping — expand for each item
                blocks.extend(self._emit_array_facts(path, spec, data, dim_contexts_available))
            else:
                fact = self._emit_simple_fact(path, spec, data)
                if fact:
                    blocks.append(fact)
        return blocks

    def _emit_simple_fact(self, path: str, spec: dict, data: dict) -> str | None:
        value = _get(data, path)
        if value is None or value == "":
            return None
        tag = spec.get("tag")
        if not tag:
            return None
        ctx = spec.get("context")
        if not ctx:
            return None
        unit_attr = ""
        decimals_attr = ""
        if "unit" in spec:
            unit_attr = f' unitRef="{_esc_attr(spec["unit"])}"'
        if "decimals" in spec:
            decimals_attr = f' decimals="{spec["decimals"]}"'
        # Format numeric values
        if "unit" in spec:
            value_str = _fmt_number(value, spec.get("decimals", 0))
        else:
            value_str = _esc(value)
        return f'    <{tag} contextRef="{_esc_attr(ctx)}"{unit_attr}{decimals_attr}>{value_str}</{tag}>'

    def _emit_array_facts(self, path: str, spec: dict, data: dict,
                          dim_contexts_available: set[str]) -> list[str]:
        # Split "shareholders[*].name" into "shareholders" + "name"
        prefix, _, suffix = path.partition("[*].")
        items = _get(data, prefix) or []
        if not isinstance(items, list):
            return []
        out: list[str] = []
        tag = spec.get("tag")
        context_pattern = spec.get("context_pattern", "")
        unit = spec.get("unit")
        decimals = spec.get("decimals")
        for idx, item in enumerate(items, start=1):
            if not isinstance(item, dict):
                continue
            value = item.get(suffix)
            if value is None or value == "":
                continue
            ctx_id = context_pattern.replace("{idx}", str(idx))
            # Skip if we didn't build a matching context
            if ctx_id not in dim_contexts_available:
                continue
            unit_attr = f' unitRef="{_esc_attr(unit)}"' if unit else ""
            decimals_attr = f' decimals="{decimals}"' if decimals is not None else ""
            if unit:
                val_str = _fmt_number(value, decimals or 0)
            else:
                val_str = _esc(value)
            out.append(f'    <{tag} contextRef="{_esc_attr(ctx_id)}"{unit_attr}{decimals_attr}>{val_str}</{tag}>')
        return out

    # ── filename ─────────────────────────────────────────────────────────────

    def _build_filename(self, data: dict) -> str:
        name = _get(data, "company.name") or "UNKNOWN_COMPANY"
        name_u = re.sub(r"[^A-Z0-9]+", "_", name.upper()).strip("_")
        filing_type = (_get(data, "reporting_period.report_type") or
                       self.tpl.get("defaults", {}).get("filing_type", "STANDALONE")).upper()
        fy_end = _get(data, "reporting_period.end_date") or ""
        fy_start = _get(data, "reporting_period.start_date") or ""
        # Format FY as e.g. 2022_23
        fy_short = ""
        try:
            sy = dt.date.fromisoformat(fy_start).year
            ey = dt.date.fromisoformat(fy_end).year
            fy_short = f"{sy}_{str(ey)[-2:]}"
        except Exception:
            fy_short = fy_end.replace("-", "_")
        form_ver = self.tpl.get("defaults", {}).get("form_version", "VI")
        return f"{name_u}_{filing_type}_GENERATED_{form_ver}_{fy_short}.xml"
